version: "3"
services:
  frontend:
    container_name: frontend
    image: botest:latest
    ports:
      - "3001:3000"
    environment:
      # DB Config
      - HOST_NAME_API=http://localhost:4000/
      - DOMAIN_NAME_API=localhost
