import "../styles/globals.css";
import "antd/dist/antd.css";
import "react-quill/dist/quill.snow.css";
import type { AppProps } from "next/app";
import { Provider } from "react-redux";
import store from "../store";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import AuthenticatedRoute from "../contexts/authenticatedRoute";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <Provider store={store}>
            <Head>
                <title>JUWAN ADMIN</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/juwanfood-logo-short.png" />
            </Head>
            <AuthenticatedRoute pathAfterFailure={"/login"}>
                <Navbar />
                <div style={{ marginLeft: "70px" }}>
                    <Header />
                    <div
                        style={{
                            padding: "20px",
                            width: "100%",
                            maxWidth: "1690px",
                            margin: "auto",
                        }}
                    >
                        <Component {...pageProps} />
                    </div>
                </div>
            </AuthenticatedRoute>
        </Provider>
    );
}

export default MyApp;
